      1 [DEBUG] org.netbeans.api:org-apache-tools-ant-module:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-apache-xml-resolver:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-intent:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-io:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-java-classpath:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-java:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-progress:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-progress-nb:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-scripting:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-search:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-templates:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-xml:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-api-xml-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-core-multiview:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-libs-asm:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-libs-lucene:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-autoupdate-services:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-autoupdate-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-classfile:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-diff:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-bracesmatching:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-codetemplates:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-completion:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-document:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-errorstripe-api:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-fold:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-guards:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-indent:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-indent-project:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-indent-support:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-lib:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-mimelookup:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-settings:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-settings-lib:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-editor-util:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-javahelp:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-lexer:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-platform:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-platform-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-project:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-project-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-source:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-java-sourceui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-jumpto:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-lexer:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-libs-corba-omgapi:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-options-api:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-parsing-api:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-parsing-indexing:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-project-ant:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-project-ant-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-projectapi:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-project-libraries:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-project-libraries-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-projectuiapi-base:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-projectuiapi:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-queries:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-refactoring-api:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-refactoring-java:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-sampler:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-modules-xml-catalog:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-spi-navigator:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-spi-quicksearch:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-spi-tasklist:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-swing-outline:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-swing-plaf:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-netbeans-swing-tabcontrol:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-actions:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-awt:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-dialogs:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-execution:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-explorer:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-filesystems-nb:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-io:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-loaders:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-modules:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-nodes:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-text:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-util-ui:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.api:org-openide-windows:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-editor-errorstripe:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-editor-settings-storage:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-java-completion:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-java-editor-base:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-java-preprocessorbridge:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-masterfs:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-options-editor:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-options-keymap:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-parsing-lucene:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
      1 [DEBUG] org.netbeans.modules:org-netbeans-modules-whitelist:jar:RELEASE122 omitted as NetBeans module dependency, not a direct one. Declare it in the pom for inclusion.
